import type { FnCategory } from '../core/types';

/**
 * Extended function catalog from the Bloomberg feature inventory
 * (docs/BLOOMBERG_TERMINAL_FEATURES.md) — real mnemonics registered as
 * navigable roadmap entries so the command surface knows the whole spec.
 * Building one = writing its screen and registering it live.
 */

type Entry = [string, string, string];

const C = (category: FnCategory, entries: Entry[]) =>
  entries.map(([m, n, d]) => ({ mnemonic: m, name: n, category, description: d }));

export const CATALOG = [
  ...C('System', [
    ['BPS', 'Cheat Sheets', 'Product documentation and cheat sheets by asset class.'],
    ['DOCS', 'Document Search', 'Search help pages and documentation.'],
    ['PDFC', 'Copy Defaults', 'Copy personal defaults between profiles.'],
    ['CNFG', 'Screen Config', 'Panel, font and color configuration.'],
    ['TZDF', 'Time Zone', 'Set the session time zone.'],
    ['LANG', 'Language', 'Interface language settings.'],
    ['PRTS', 'Print Settings', 'Configure printing of screens.'],
    ['STO', 'Copy Security', 'Copy the loaded security to paste in another panel.'],
    ['RCL', 'Paste Security', 'Paste a copied security into this panel.'],
    ['HDSK', 'Help Desk', 'Raise and track support tickets.'],
    ['TMSG', 'System Status', 'Terminal message of the day and system health.'],
    ['UUF', 'User Profile', 'Your profile and preferences.'],
    ['SPDL', 'Speed Dial', 'Favorite contacts for instant messaging.'],
    ['BMC', 'Market Concepts', 'Interactive markets e-learning and certification.'],
    ['PRPL', 'Profile & CV', 'Professional profile for the network directory.'],
    ['JOBS', 'Job Listings', 'Finance job postings.'],
    ['LLP', 'Launchpad', 'Dockable always-on monitor/chart/news components.'],
    ['MONI', 'Monitor Manager', 'Manage saved monitors and views.'],
    ['DRQS', 'Data Request', 'Request data additions or corrections.'],
    ['FLY', 'Flight Tracker', 'Terminal-lore easter egg: track flights.'],
    ['POSH', 'Marketplace', 'Terminal-lore easter egg: classifieds for the desk.'],
    ['DINE', 'Restaurants', 'Terminal-lore easter egg: reviews near the office.'],
    ['BOAT', 'Yacht Listings', 'Terminal-lore easter egg: because Bloomberg has one.'],
    ['SNOW', 'Ski Reports', 'Terminal-lore easter egg: mountain conditions.'],
  ]),
  ...C('Markets', [
    ['GMM', 'Global Macro Movers', 'Biggest cross-asset moves right now.'],
    ['IMAP', 'Intraday Market Map', 'Sector heat-map treemap of the market.'],
    ['MKTP', 'Market Map Globe', 'World map visualization of market moves.'],
    ['WBF', 'World Bond Futures', 'Global bond futures board.'],
    ['WIR', 'World Rate Futures', 'Short-term interest-rate futures board.'],
    ['EPFR', 'Fund Flows', 'Cross-border fund-flow analytics.'],
    ['MMR', 'Money Market Rates', 'Money-market rates monitor.'],
    ['GLC', 'Global Liquidity', 'Liquidity condition monitors.'],
    ['SECF', 'Security Finder', 'Cross-asset security search.'],
    ['QRM', 'Trade Recap Depth', 'Tick-by-tick recap with market depth.'],
    ['TSM', 'Trade Summary Matrix', 'Venue breakdown of executed volume.'],
    ['VWAP', 'VWAP Analytics', 'Volume-weighted average price analysis.'],
    ['MDM', 'Market Depth', 'Level-2 order book display.'],
    ['EVTS', 'Event Calendar', 'Earnings calls, conferences, corporate events.'],
    ['CACT', 'Corporate Action Feed', 'Stream of corporate actions across the market.'],
  ]),
  ...C('Equities', [
    ['MODL', 'Company Model', 'Consensus-driven projection model by line item.'],
    ['EEB', 'Broker Estimates', 'Estimate detail broker by broker.'],
    ['EA', 'Earnings Implied Move', 'Options-implied move into the earnings print.'],
    ['BICS', 'Industry Classification', 'Sector/industry classification browser.'],
    ['CAST', 'Capital Structure', 'Debt stack and maturity wall visualization.'],
    ['ISSD', 'Issuer Description', 'Credit-oriented issuer profile.'],
    ['RELS', 'Related Securities', 'All instruments of one issuer.'],
    ['AGGD', 'Aggregated Debt', 'Aggregate debt view for an issuer.'],
    ['MGMT', 'Management & Board', 'Executives and directors with bios.'],
    ['PHDC', 'Holders Detail', 'Institutional holder positions and changes.'],
    ['INSD', 'Insider Activity', 'Insider transaction feed.'],
    ['WACC', 'Cost of Capital', 'Weighted average cost of capital calculator.'],
    ['DDM', 'Dividend Discount Model', 'Intrinsic valuation from projected dividends.'],
    ['GEO', 'Revenue Geography', 'Geographic revenue segmentation.'],
    ['LITI', 'Litigation Tracker', 'Company litigation exposure.'],
    ['PBAR', 'Peer Bar Charts', 'Visual peer comparisons.'],
    ['GRR', 'Group Return Ranking', 'Sector and index total-return ranking.'],
    ['PPC', 'Price Band Charts', 'P/E and valuation band charting.'],
    ['EQBT', 'Screen Backtest', 'Backtest an equity screen through history.'],
    ['FSCO', 'Factor Scores', 'Style-factor scoring per security.'],
    ['PE', 'Private Markets', 'Private equity and private company data.'],
    ['DRSK', 'Default Risk', '1-year default probability and credit health.'],
    ['HFND', 'Hedge Fund Database', 'Hedge-fund profiles and returns.'],
    ['NAV', 'Fund NAV History', 'Net asset value history for funds.'],
    ['ETF', 'ETF Hub', 'Flows, creations, premium/discount for ETFs.'],
    ['FREP', 'Fund Holdings', 'Fund replication and holdings look-through.'],
    ['FPC', 'Fund Comparison', 'Compare fund performance and fees.'],
  ]),
  ...C('Fixed Income', [
    ['YASN', 'Structured Yield', 'Yield analysis for notes and structured paper.'],
    ['ASW', 'Asset Swap Calc', 'Asset-swap spread calculator.'],
    ['OAS1', 'OAS Analytics', 'Option-adjusted spread for callables.'],
    ['FIHZ', 'Horizon Analysis', 'Total-return horizon scenarios for bonds.'],
    ['BVAL', 'Evaluated Pricing', 'Evaluated bond pricing with confidence scores.'],
    ['TDH', 'Trade History', 'TRACE-style print history for a bond.'],
    ['CSHF', 'Cash Flows', 'Bond cash-flow schedule.'],
    ['USSW', 'US Rates Composite', 'One-screen US swaps and rates composite.'],
    ['IRSB', 'Swap Rates Board', 'Live interest-rate swap board.'],
    ['ILBE', 'Inflation Breakevens', 'Breakeven inflation curves.'],
    ['DOTS', 'Fed Dot Plot', 'FOMC projection dot plot.'],
    ['CDX', 'Credit Indices', 'CDX/iTraxx index monitors and skew.'],
    ['RATD', 'Rating Definitions', 'Agency rating scale methodology.'],
    ['DIS', 'Distressed Monitor', 'Distressed-debt market monitor.'],
    ['PREL', 'Deal Pipeline', 'Preliminary new-issue announcements.'],
    ['LEAG', 'League Tables', 'Underwriting league tables.'],
    ['COVR', 'Covenant Analysis', 'Bond covenant review.'],
    ['RESL', 'Restructuring Tracker', 'Liability management and restructurings.'],
    ['MIFA', 'Muni Issuer Analysis', 'Municipal issuer financials.'],
    ['DEAL', 'Muni Calendar', 'New municipal deal calendar.'],
    ['CLC', 'MBS Collateral', 'Mortgage pool collateral composition.'],
    ['CFT', 'CMO Cash Flows', 'Tranche cash-flow tables.'],
    ['VALL', 'Prepay Vectors', 'Vector analysis across prepayment scenarios.'],
    ['YT', 'MBS Yield Table', 'Price/yield across prepayment speeds.'],
    ['CPH', 'Prepay History', 'Historical prepayment speeds.'],
    ['CMO', 'CMO Explorer', 'Structured deal and tranche explorer.'],
    ['RRRA', 'Repo Calculator', 'Repo rate and haircut math.'],
    ['BSR', 'Repo Rates', 'Repo market rate monitor.'],
    ['MMCV', 'MM Curves', 'Money-market curve monitors.'],
  ]),
  ...C('Derivatives', [
    ['OVML', 'FX Option Pricer', 'Vanilla and barrier FX option pricing.'],
    ['OVSN', 'Note Pricer', 'Structured-note valuation.'],
    ['HIVG', 'Implied Vol History', 'Historical implied volatility graph.'],
    ['HVT', 'Vol Table', 'Historical volatility table across windows.'],
    ['TRMS', 'Vol Term Structure', 'VIX/vol futures term-structure monitor.'],
    ['EXS', 'Expiration Schedule', 'Listed derivative expiry calendar.'],
    ['FWCM', 'Forward Matrix', 'Forward curve matrix across assets.'],
    ['XLTP', 'Template Library', 'Pricing template library.'],
    ['SWPR', 'Swap Rates', 'Swap rate monitors by currency.'],
    ['DSWP', 'Swap Dashboards', 'Swap curve dashboards.'],
    ['MARS', 'Multi-Asset Risk', 'Portfolio-level derivatives risk and stress.'],
  ]),
  ...C('FX', [
    ['FXIP', 'FX Info Portal', 'FX market information hub.'],
    ['FXC', 'Cross Matrix', 'Currency cross-rate matrix.'],
    ['FXCT', 'Carry Analytics', 'FX carry-trade analysis.'],
    ['CIX', 'Custom Index', 'Build custom baskets and spreads as tickers.'],
    ['REGN', 'Real Exchange Rates', 'Real effective exchange-rate data.'],
    ['EMFX', 'EM Currencies', 'Emerging-market FX dashboards.'],
  ]),
  ...C('Commodities', [
    ['NRG', 'Energy Hub', 'Crude, products, gas and power dashboards.'],
    ['METL', 'Metals Hub', 'Base and precious metals dashboards.'],
    ['AGS', 'Agriculture Hub', 'Grains and softs dashboards.'],
    ['CTM', 'Contract Tables', 'Futures contract tables across markets.'],
    ['COSY', 'Supply & Inventory', 'Inventory and supply-demand releases.'],
    ['FRHT', 'Freight Rates', 'Baltic indices and tanker rates.'],
    ['OILP', 'Oil Snapshot', 'One-screen oil market view.'],
    ['CARB', 'Carbon Markets', 'Emissions and carbon-credit markets.'],
    ['BMAP', 'Asset Maps', 'Ships, rigs, pipelines and refineries on the map.'],
  ]),
  ...C('Economics', [
    ['ECOF', 'Data Finder', 'Browse all economic time series.'],
    ['ECOS', 'Economist Detail', 'Individual economist estimates.'],
    ['GEW', 'Global Watch', 'Global economic conditions monitor.'],
    ['ECWB', 'Econ Workbench', 'Chart and transform macro series.'],
    ['GPCA', 'Cycle Analysis', 'Global PMI and cycle dashboards.'],
    ['NSDX', 'Nowcasts', 'News-derived GDP tracking.'],
    ['COUN', 'Country Risk', 'Country risk profiles.'],
    ['SOVR', 'Sovereign Ratings', 'Sovereign ratings and CDS overview.'],
    ['CBRT', 'CB Rates', 'Central-bank policy rates worldwide.'],
    ['BOE', 'Bank of England', 'BOE hub: decisions, minutes, speakers.'],
    ['ECB', 'European Central Bank', 'ECB hub: decisions, minutes, speakers.'],
    ['BOJ', 'Bank of Japan', 'BOJ hub: decisions, minutes, speakers.'],
  ]),
  ...C('News', [
    ['NH', 'News Topics', 'News browsing by ticker or topic.'],
    ['TNI', 'Topic Combine', 'Intersect two news topic codes.'],
    ['NRR', 'News Sentiment Score', 'News-derived sentiment per security.'],
    ['BRIEFS', 'Newsletters', 'Curated market newsletters.'],
    ['RES', 'Research Portal', 'Broker and third-party research.'],
    ['BI', 'Industry Intelligence', 'Analyst dashboards per industry.'],
    ['BNEF', 'Energy Transition', 'New-energy research and data.'],
    ['DSCO', 'Document Search', 'Search filings and transcripts.'],
    ['CF', 'Company Filings', 'Regulatory filings for the issuer.'],
    ['EDF', 'Disclosure Filings', 'Equity disclosure documents.'],
    ['LIVE', 'Live TV', 'Live market television stream.'],
    ['AV', 'Audio / Video', 'Event replays, clips and podcasts.'],
    ['SQUAWK', 'Market Squawk', 'Live audio market commentary.'],
    ['READ', 'Most Read', 'Trending stories across users.'],
    ['NT', 'News Trends', 'Headline volume trends over time.'],
  ]),
  ...C('Portfolio', [
    ['RSK', 'Risk Models', 'Factor risk model detail.'],
    ['HFA', 'Style Analysis', 'Returns-based style analysis.'],
    ['PC', 'Performance Calc', 'Performance calculation and GIPS views.'],
    ['BRC', 'Reconciliation', 'Position reconciliation tools.'],
    ['AIM', 'Order Management', 'Buy-side OMS: orders, compliance, allocations.'],
    ['PLST', 'Portfolio List', 'All portfolios in the account.'],
    ['BBU', 'Position Upload', 'Bulk position upload.'],
  ]),
  ...C('Trading', [
    ['FIT', 'FI Trading Hub', 'Click-to-trade government bond streams.'],
    ['BOLT', 'Bond ATS', 'All-to-all bond trading.'],
    ['BMTF', 'Regulated Venues', 'MTF/SEF execution venues.'],
    ['TOMS', 'Sell-Side OMS', 'Inventory, axes and trade management.'],
    ['AXES', 'Dealer Axes', 'Aggregated dealer axes.'],
    ['VCON', 'Trade Confirms', 'Voice-trade confirmation matching.'],
    ['STP', 'Straight-Through', 'FIX network and allocation flows.'],
    ['TCA', 'Transaction Costs', 'Execution cost analysis.'],
    ['RULE', 'Pre-Trade Compliance', 'Order compliance rules.'],
  ]),
  ...C('Communication', [
    ['IBXS', 'Chat Blast', 'Broadcast to many chats at once.'],
    ['BIO', 'Person Profile', 'Bio, employment history and coverage.'],
    ['MEET', 'Meetings', 'Roadshow and meeting scheduling.'],
    ['NOTES', 'Shared Notes', 'Collaborative notes on securities.'],
  ]),
] as Array<{ mnemonic: string; name: string; category: FnCategory; description: string }>;
